
all:
	+@echo "Please build from the root directory."

# This will place the web files required by gproc into a .go file
# so that gproc can be provided in one binary
pre-build:
	

build:
	# Nothing to do here

clean:
	# placeholder to keep the top level makefile happy
